### ISSUE TITLE
IE11 doesn't support grid level alignment "justify-items", "align-items"

### ISSUE THREAD

**Issue by MikeVaz** [ZS/powergrid#13]
But it supports cell level alignment with `grid-column-align` `grid-row-align`.

Spec:
https://www.w3.org/TR/2011/WD-css3-grid-layout-20110407/#grid-item-alignment

**Comment by MikeVaz** [comment]
In powergrid :1234: we created a workaround for this problem. 

We defined a class that can be applied at a grid container level to set alignment of grid items.

Here is an example...

```html
<div class="pg-grid">
    <div>1</div>
    <div>2</div>
    <div>3</div>
    <div class="pg-align-self-end pg-justify-self-end">4</div>
</div>
```
```css
/* Alignment */
.pg-justify-start > *  {
  justify-self: start;
  -ms-grid-column-align: start;
}
.pg-align-start > *  {
  align-self: start;
  -ms-grid-row-align: start;
}
.pg-grid > .pg-align-self-start {
  align-self: start;
  -ms-grid-row-align: start;
}
.pg-grid > .pg-justify-self-start {
  justify-self: start;
  -ms-grid-column-align: start;
}

.pg-justify-end > *  {
  justify-self: end;
  -ms-grid-column-align: end;
}
.pg-align-end > *  {
  align-self: end;
  -ms-grid-row-align: end;
}
.pg-grid > .pg-align-self-end {
  align-self: end;
  -ms-grid-row-align: end;
}
.pg-grid > .pg-justify-self-end {
  justify-self: end;
  -ms-grid-column-align: end;
}

.pg-justify-center > *  {
  justify-self: center;
  -ms-grid-column-align: center;
}
.pg-align-center > *  {
  align-self: center;
  -ms-grid-row-align: center;
}
.pg-grid > .pg-align-self-center {
  align-self: center;
  -ms-grid-row-align: center;
}
.pg-grid > .pg-justify-self-center {
  justify-self: center;
  -ms-grid-column-align: center;
}

.pg-justify-stretch > *  {
  justify-self: stretch;
  -ms-grid-column-align: stretch;
}
.pg-align-stretch > *  {
  align-self: stretch;
  -ms-grid-row-align: stretch;
}
.pg-grid > .pg-align-self-stretch {
  align-self: stretch;
  -ms-grid-row-align: stretch;
}
.pg-grid > .pg-justify-self-stretch {
  justify-self: stretch;
  -ms-grid-column-align: stretch;
}
```

...would result in something like this

![image](https://user-images.githubusercontent.com/4261252/42973657-8ed04b84-8b79-11e8-84b9-f31ded26da46.png)

[Demo](https://zs.github.io/powergrid/index.html?q=eyJuYW1lIjoiUG93ZXIgR3JpZCIsInZlcnNpb24iOiIwLjEuMCIsInVybCI6Imh0dHBzOi8vZ2l0aHViLmNvbS9aUy9wb3dlcmdyaWQvIiwiY29scyI6WyIxMDBweCIsIjEwMHB4Il0sInJvd3MiOlsiMTAwcHgiLCIxMDBweCJdLCJhbGlnbiI6ImNlbnRlciIsImp1c3RpZnkiOiJjZW50ZXIiLCJjZWxscyI6W3sidGV4dCI6IjEifSx7InRleHQiOiIyIn0seyJ0ZXh0IjoiMyJ9LHsidGV4dCI6IjQiLCJhbGlnbiI6ImVuZCIsImp1c3RpZnkiOiJlbmQifV0sInByZWZpeCI6InBnLSJ9)
