### ISSUE TITLE
Inconsistent behavior in IE11 and other browsers when grid trek size "auto" is used.

### ISSUE THREAD

**Issue by MikeVaz** [ZS/powergrid#16]
Use the code below 

```html
<div class="pg-grid">
    <div>1</div>
    <div>2</div>
    <div>3</div>
    <div>4</div>
</div>
```
```css
.pg-grid {
  display: grid;
  display: -ms-grid;
  grid-template-columns: auto auto;
  -ms-grid-columns: auto auto;
  grid-template-rows: auto auto;
  -ms-grid-rows: auto auto;
}
```
Or this [demo page](https://zs.github.io/powergrid/index.html?q=eyJuYW1lIjoiUG93ZXIgR3JpZCIsInZlcnNpb24iOiIwLjEuMCIsInVybCI6Imh0dHBzOi8vZ2l0aHViLmNvbS9aUy9wb3dlcmdyaWQvIiwiY29scyI6WyJhdXRvIiwiYXV0byJdLCJyb3dzIjpbImF1dG8iLCJhdXRvIl0sImNlbGxzIjpbeyJ0ZXh0IjoiMSJ9LHsidGV4dCI6IjIifSx7InRleHQiOiIzIn0seyJ0ZXh0IjoiNCJ9XSwicHJlZml4IjoicGctIn0=)

Browser will display it differently.

Chrome:
![image](https://user-images.githubusercontent.com/4261252/43017684-9abba846-8c1c-11e8-9a1c-855ca335b2cc.png)

IE11
![image](https://user-images.githubusercontent.com/4261252/43017813-217a6304-8c1d-11e8-908c-752475f28988.png)

**Comment by MikeVaz** [comment]
:1234: we suggest a workaround to use `min-max(min-content, 1fr)` for trek size or similar in such cases.

```css
.pg-grid {
  display: grid;
  display: -ms-grid;
  grid-template-columns: minmax(min-content,1fr) minmax(min-content,1fr);
  -ms-grid-columns: minmax(min-content,1fr) minmax(min-content,1fr);
  grid-template-rows: minmax(min-content,1fr) minmax(min-content,1fr);
  -ms-grid-rows: minmax(min-content,1fr) minmax(min-content,1fr);
}
```

Use this demo [configuration](https://zs.github.io/powergrid/index.html?q=eyJuYW1lIjoiUG93ZXIgR3JpZCIsInZlcnNpb24iOiIwLjEuMCIsInVybCI6Imh0dHBzOi8vZ2l0aHViLmNvbS9aUy9wb3dlcmdyaWQvIiwiY29scyI6WyJtaW5tYXgobWluLWNvbnRlbnQsMWZyKSIsIm1pbm1heChtaW4tY29udGVudCwxZnIpIl0sInJvd3MiOlsibWlubWF4KG1pbi1jb250ZW50LDFmcikiLCJtaW5tYXgobWluLWNvbnRlbnQsMWZyKSJdLCJjZWxscyI6W3sidGV4dCI6IjEifSx7InRleHQiOiIyIn0seyJ0ZXh0IjoiMyJ9LHsidGV4dCI6IjQifV0sInByZWZpeCI6InBnLSJ9)

![image](https://user-images.githubusercontent.com/4261252/43018008-c0fe85b8-8c1d-11e8-9ae3-fd5527561192.png)
