### ISSUE TITLE
IE11 doesn't support grid gutters.

### ISSUE THREAD

**Issue by MikeVaz** [ZS/powergrid#18]
New spec
https://www.w3.org/TR/css-grid-1/#gutters

Older IE11 spec doesn't have it:
https://www.w3.org/TR/2011/WD-css3-grid-layout-20110407/#grid-concepts

**Comment by MikeVaz** [comment]
In powergrid :1234:  we use box models of grid items to compensate.

HTML
```html
<div class="pg-grid">
    <div>1</div>
    <div>2</div>
    <div>3</div>
    <div>4</div>
    <div>5</div>
    <div>6</div>
</div>
```

CSS
```css 
...

/* Decorating grid items with space */
.pg-grid>div {
  ...
  border: 1px solid #c0c0c0;
  padding: 10px;
  margin: 5px;
}

/* Grid lines template */
.pg-grid {
  display: grid;
  display: -ms-grid;
  grid-template-columns: 100px 100px 100px;
  -ms-grid-columns: 100px 100px 100px;
  grid-template-rows: 100px 100px;
  -ms-grid-rows: 100px 100px;
}
```

![image](https://user-images.githubusercontent.com/4261252/43099189-f1f75058-8e86-11e8-8220-41c05fc1d399.png)

[Demo](https://zs.github.io/powergrid/index.html?q=eyJuYW1lIjoiUG93ZXIgR3JpZCIsInZlcnNpb24iOiIwLjEuMCIsInVybCI6Imh0dHBzOi8vZ2l0aHViLmNvbS9aUy9wb3dlcmdyaWQvIiwiY29scyI6WyIxMDBweCIsIjEwMHB4IiwiMTAwcHgiXSwicm93cyI6WyIxMDBweCIsIjEwMHB4Il0sImNlbGxzIjpbeyJ0ZXh0IjoiMSJ9LHsidGV4dCI6IjIifSx7InRleHQiOiIzIn0seyJ0ZXh0IjoiNCJ9LHsidGV4dCI6IjUifSx7InRleHQiOiI2In1dLCJwcmVmaXgiOiJwZy0ifQ==)
