### ISSUE TITLE
Inconsistent behavior in IE11 and other browsers when 'fit-content' is applied to a column/row in the grid template

### ISSUE THREAD

**Issue by php1990** [ZS/powergrid#21]
Consider the following snippet:

```html
<div class="pg-grid">
    <div>100px</div>
    <div>fit-content(300px)</div>
    <div>1fr</div>
</div>
```

```css
.pg-grid {
  display: grid;
  display: -ms-grid;
  grid-template-columns: 100px fit-content(300px) 1fr;
  -ms-grid-columns: 100px fit-content(300px) 1fr;
  grid-template-rows: minmax(max-content,1fr);
  -ms-grid-rows: minmax(max-content,1fr);
}
```

Alternatively, check [this](https://zs.github.io/powergrid/?q=eyJuYW1lIjoiUG93ZXIgR3JpZCIsInZlcnNpb24iOiIwLjEuMCIsInVybCI6Imh0dHBzOi8vZ2l0aHViLmNvbS9aUy9wb3dlcmdyaWQvIiwiY29scyI6WyIxMDBweCIsImZpdC1jb250ZW50KDMwMHB4KSIsIjFmciJdLCJyb3dzIjpbIm1pbm1heChtYXgtY29udGVudCwxZnIpIl0sImFsaWduIjoic3RyZXRjaCIsImp1c3RpZnkiOiJzdHJldGNoIiwiY2VsbHMiOlt7InRleHQiOiIxMDBweCJ9LHsidGV4dCI6ImZpdC1jb250ZW50KDMwMHB4KSJ9LHsidGV4dCI6IjFmciJ9XSwicHJlZml4IjoicGctIn0=) page.

Observe the difference in browser behaviors.

Chrome:
![image](https://user-images.githubusercontent.com/37831642/43191076-0e108d1c-9018-11e8-821b-0990cd9685f0.png)

IE11:
![image](https://user-images.githubusercontent.com/37831642/43191145-2f009bfc-9018-11e8-9ee6-a1fa57fff995.png)
