### ISSUE TITLE
Create a file for decorate styles used on the demo page.

### ISSUE THREAD

**Issue by MikeVaz** [ZS/powergrid#28]
We have styles in the html of the demo page that help to picture the grid.

```css
/* General styles */
body,
html {
	padding: 0;
	margin: 0;
	height: 100%;
	min-height: 100%;
	background: rgba(50, 50, 50, 0.5);
	font-family: Roboto, Arial, Helvetica, sans-serif;
}

.fluid {
	width: 100%;
	height: 100%;
	overflow:auto; /* this helps to stretch container */
}

/* Decorate cells for better identification */
#grid {
	background: transparent;
}

#grid>div {
	background: white;
	padding: 10px;
	border: 1px solid #c0c0c0;
	box-shadow: 1px 1px 1px #000;
	border-radius: 10px;
	color: #000;
	text-shadow: 1px 1px #c0c0c0;
	margin: 5px;
	cursor: pointer;
}

#grid>div:nth-child(n+1) {
	background: rgba(0, 255, 0, 0.5);
	border: 1px solid green;
}

#grid>div:nth-child(2n) {
	background: rgba(0, 255, 255, 0.5);
	border: 1px solid lightblue;
}

#grid>div:nth-child(3n) {
	background: rgba(0, 0, 255, 0.5);
	border: 1px solid blue;
}

#grid>div:nth-child(4n) {
	background: rgba(255, 0, 255, 0.5);
	border: 1px solid purple;
}

#grid>div:nth-child(5n) {
	background: rgba(255, 0, 0, 0.5);
	border: 1px solid red;
}

#grid>div:nth-child(6n) {
	background: rgba(255, 127, 0, 0.5);
	border: 1px solid orange;
}

#grid>div:nth-child(7n) {
	background: rgba(255, 255, 0, 0.5);
	border: 1px solid yellow;
}

#grid>div:nth-child(8n) {
	background: rgba(0, 255, 0, 0.5);
	border: 1px solid green;
}
#grid>div:nth-child(n).selected-grid{
	border: 2px dashed black;
}
```

But they might be handy for playgrounds like [this](http://jsfiddle.net/w0s4xmc0/25167/).

It might be tricky to do that since we use it to generate the full page HTML to copy
