### ISSUE TITLE
IE11 doesn't support auto placement of grid items

### ISSUE THREAD

**Issue by MikeVaz** [ZS/powergrid#9]
Some more details
https://stackoverflow.com/questions/45436398/css-grid-auto-placement-in-ie-edge

Spec
https://www.w3.org/TR/2011/WD-css3-grid-layout-20110407/

**Comment by MikeVaz** [comment]
A work around we use in the **powegrid** is to automatically place items based on their order in the container.

```html
<div class="pg-grid">
    <div>Cell-1-1</div>
    <div>Cell-1-2</div>
    <div class="pg-col-2">Cell-2-4</div>
</div>
```

```css
/* Auto placement of grid cells based on the order */
.pg-grid > :nth-child(2n+1) {
  grid-column-start: 1;
  -ms-grid-column: 1;
}

.pg-grid > :nth-child(2n+2) {
  grid-column-start: 2;
  -ms-grid-column: 2;
}

.pg-grid > :nth-child(n+1) {
  grid-row-start: 1;
  -ms-grid-row: 1;
}

.pg-grid > :nth-child(n+3) {
  grid-row-start: 2;
  -ms-grid-row: 2;
}
```

[Example](https://zs.github.io/powergrid/?q=eyJuYW1lIjoiUG93ZXIgR3JpZCIsInZlcnNpb24iOiIwLjEuMCIsInVybCI6Imh0dHBzOi8vZ2l0aHViLmNvbS9aUy9wb3dlcmdyaWQvIiwiY29scyI6WyIxZnIiLCIxZnIiXSwicm93cyI6WyIxZnIiLCIxZnIiXSwiY2VsbHMiOlt7InRleHQiOiJDZWxsLTEtMSJ9LHsidGV4dCI6IkNlbGwtMS0yIn0seyJ0ZXh0IjoiQ2VsbC0yLTQiLCJjb2wiOjJ9XSwicHJlZml4IjoicGctIn0=)

The limitation of this approach is when you start span several grid cells. Use explicit placement in this case.
